// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Oculi",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Oculi",
            targets: ["AppModule"],
            bundleIdentifier: "com.evan.crow.Oculi",
            teamIdentifier: "6A2M79984Q",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "Oculi uses your Microphone for dictation features."),
                .speechRecognition(purposeString: "Oculi uses Speech Recognition for dictation features."),
                .camera(purposeString: "Oculi uses your front facing camera to detect and track your face.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
